### ISSUE TITLE
Locale name for Japanese

### ISSUE THREAD

**Issue by diginatu** [impleCode/ecommerce-product-catalog#6]
Hello, thank you for your great plugin.

I confirmed that some lang file was added.
But WordPress locale for Japanese is just "ja" not "ja_JA".
You can see the list of all langages.
http://wpcentral.io/internationalization/

So I think you should rename the file to "al-ecommerce-product-catalog-ja.mo".

Thank you in advance.

**Comment by ndre** [comment]
Hi, 

Thank you for the info. It is fixed now.
