### ISSUE TITLE
Change "products" URL slug

### ISSUE THREAD

**Issue by IdleMuse** [impleCode/ecommerce-product-catalog#7]
Although you can change the Categories Parent URL in the settings, so categories appear as /my-custom-slug/category-name/, products seem to be hardcoded to be /products/product-name.

Would it be possible to add a field to allow you to customise the Parent URL for products?

**Comment by ndre** [comment]
The products parent is set by product listing page in settings.

**Comment by IdleMuse** [comment]
That's only true if you have Product Listing Page enabled; I'm using a custom product listing page with the shortcode.

**Comment by ndre** [comment]
Are you sure? It should work even if your Product Listing Page is disabled.
